# Generated by Django 2.1.7 on 2019-03-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FilePathField()),
                ('face_detect_result', models.TextField()),
                ('body_detect_result', models.TextField()),
            ],
        ),
    ]
