# Generated by Django 2.1.7 on 2019-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img')),
                ('rect_body_img', models.ImageField(upload_to='img')),
                ('face_detect_result', models.TextField()),
                ('body_detect_result', models.TextField()),
            ],
        ),
    ]
