# Generated by Django 2.1.7 on 2019-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mie_monitor', '0002_auto_20190314_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file_path',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
